# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - workledger-proto-win

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache next/cache
        uses: actions/cache@v3
        with:
          path: '**/.next/cache'
          key: ${{ runner.os }}-next/cache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-next/cache-${{ hashFiles('**/package-lock.json') }}-
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: npm install, build, and test
        run: |
          npm ci
          npm run build

      - name: Zip artifact for deployment
        run: Compress-Archive -Path .\* -DestinationPath .\release.zip
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .\release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'github-test-by-plain-nextjs'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          
      - name: unzip artifact for deployment
        run: 7z x release.zip

      - name: remove artifact
        run: rm release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'workledger-proto-win'
          slot-name: 'github-test-by-plain-nextjs'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68DC4670C36441A7B925AF086CE9F468 }}